apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/api
  - ../../base/worker
  - ../../base/frontend

images:
  - name: ghcr.io/bilalwaheed24/opspilot-api
    newTag: latest
  - name: ghcr.io/bilalwaheed24/opspilot-worker
    newTag: latest
  - name: ghcr.io/bilalwaheed24/opspilot-frontend
    newTag: latest
