apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opspilot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bilalwaheed24/opspilot
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
